version: "3.7"

volumes:
  npm-data:
  npm-ssl:
  npm-db:

networks:
  frontend:
    # add this if the network is already existing!
    # external: true
  backend:
    # add this if the network is already existing!
    # external: true

secrets:
  # Secrets are single-line text files where the sole content is the secret
  # Paths in this example assume that secrets are kept in local folder called ".secrets"
  DB_ROOT_PWD:
    file: .secrets/db_root_pwd.txt
  MYSQL_PWD:
    file: .secrets/mysql_pwd.txt
    
services:
  npm-app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    depends_on:
      - npm-db
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
      - "8000:8000"
      - "9443:9443"
      - "9000:9000"
      #- "3080:3080"
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    environment:
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      #- DB_MYSQL_PASSWORD=C4MrisGODYi6WjgA5793Aews4kuciW
      DB_MYSQL_PASSWORD__FILE: /run/secrets/MYSQL_PWD
      DB_MYSQL_NAME: "npm"
    volumes:
      - npm-data:/data
      - npm-ssl:/etc/letsencrypt
    secrets:
      - MYSQL_PWD
    networks:
      - frontend
      - backend

  npm-db:
    image: jc21/mariadb-aria:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD__FILE: /run/secrets/DB_ROOT_PWD
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD__FILE: /run/secrets/MYSQL_PWD
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "npm", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5 
    volumes:
      - npm-db:/var/lib/mysql
    secrets:
      - DB_ROOT_PWD
      - MYSQL_PWD
    networks:
      - backend
      
